// This file is auto-generated by generateHeroExports.js. Do not edit manually.

import ana from './ana.png';
import ashe from './ashe.png';
import baptiste from './baptiste.png';
import bastion from './bastion.png';
import brigitte from './brigitte.png';
import cassidy from './cassidy.png';
import doomfist from './doomfist.png';
import dva from './dva.png';
import echo from './echo.png';
import freja from './freja.png';
import genji from './genji.png';
import hanzo from './hanzo.png';
import hazard from './hazard.png';
import illari from './illari.png';
import junkerqueen from './junkerqueen.png';
import junkrat from './junkrat.png';
import juno from './juno.png';
import kiriko from './kiriko.png';
import lifeweaver from './lifeweaver.png';
import lucio from './lucio.png';
import mauga from './mauga.png';
import mei from './mei.png';
import mercy from './mercy.png';
import moira from './moira.png';
import orisa from './orisa.png';
import pharah from './pharah.png';
import ramattra from './ramattra.png';
import reaper from './reaper.png';
import reinhardt from './reinhardt.png';
import roadhog from './roadhog.png';
import sigma from './sigma.png';
import sojourn from './sojourn.png';
import soldier76 from './soldier76.png';
import sombra from './sombra.png';
import symmetra from './symmetra.png';
import torbjorn from './torbjorn.png';
import tracer from './tracer.png';
import venture from './venture.png';
import widowmaker from './widowmaker.png';
import winston from './winston.png';
import wreckingball from './wreckingball.png';
import zarya from './zarya.png';
import zenyatta from './zenyatta.png';

const heroPortraits = {
    ana,
    ashe,
    baptiste,
    bastion,
    brigitte,
    cassidy,
    doomfist,
    dva,
    echo,
    freja,
    genji,
    hanzo,
    hazard,
    illari,
    junkerqueen,
    junkrat,
    juno,
    kiriko,
    lifeweaver,
    lucio,
    mauga,
    mei,
    mercy,
    moira,
    orisa,
    pharah,
    ramattra,
    reaper,
    reinhardt,
    roadhog,
    sigma,
    sojourn,
    soldier76,
    sombra,
    symmetra,
    torbjorn,
    tracer,
    venture,
    widowmaker,
    winston,
    wreckingball,
    zarya,
    zenyatta,
};

export default heroPortraits;
