// This file is auto-generated by generatePlayerImages.js. Do not edit manually.

import OldOcean_team from "./Old Ocean/players/team_logo.png";
import onsidegaming_achieve from "./onside gaming/players/achieve_서상원.webp";
import onsidegaming_ado from "./onside gaming/players/ado_천기현.webp";
import onsidegaming_attack from "./onside gaming/players/attack_김준화.webp";
import onsidegaming_irony from "./onside gaming/players/irony_김백강.webp";
import onsidegaming_Kilo from "./onside gaming/players/Kilo_정진우.webp";
import onsidegaming_opener from "./onside gaming/players/opener_안기범.webp";
import PokerFace_team from "./Poker Face/players/team_logo.png";
import T1_team from "./T1/players/team_logo.png";
import TeamFalcons_chiyo from "./Team Falcons/players/chiyo_한현석.webp";
import TeamFalcons_fielder from "./Team Falcons/players/fielder_권준.webp";
import TeamFalcons_Hanbin from "./Team Falcons/players/Hanbin_최한빈.webp";
import TeamFalcons_mer1t from "./Team Falcons/players/mer1t_최태민.webp";
import TeamFalcons_proper from "./Team Falcons/players/proper_김동현.webp";
import TeamFalcons_Prophet from "./Team Falcons/players/Prophet_김현빈.webp";
import TeamFalcons_sirmajed from "./Team Falcons/players/sirmajed_마지드알라시드.webp";
import TeamFalcons_smurf from "./Team Falcons/players/smurf_유명환_1.webp";
import TeamFalcons_SOMEONE from "./Team Falcons/players/SOMEONE_함정완.webp";
import TeamFalcons_stalk3r from "./Team Falcons/players/stalk3r_정학용.webp";
import TeamFalcons_Vindaim from "./Team Falcons/players/Vindaim_박준우.webp";
import VecSeongnam_Scarlett from "./Vec Seongnam/players/Scarlett_권문경.webp";
import VecSeongnam_seungan from "./Vec Seongnam/players/seungan_이승안.webp";
import VecSeongnam_WoochaN from "./Vec Seongnam/players/WoochaN_이우찬.webp";
import VecSeongnam_XLIM from "./Vec Seongnam/players/XLIM_윤지후.webp";
import VecSeongnam_ZeSin from "./Vec Seongnam/players/ZeSin_송윤진.webp";
import VecSeongnam_김예한 from "./Vec Seongnam/players/김예한_1.webp";
import VecSeongnam_박민호 from "./Vec Seongnam/players/박민호_1.webp";
import VecSeongnam_이우찬 from "./Vec Seongnam/players/이우찬_1.webp";
import ZetaDivision_alphayi from "./Zeta Division/players/alphayi_김준1.webp";
import ZetaDivision_bernar from "./Zeta Division/players/bernar_신세원2.webp";
import ZetaDivision_FARMER from "./Zeta Division/players/FARMER_김예한.webp";
import ZetaDivision_flora from "./Zeta Division/players/flora_임영우.webp";
import ZetaDivision_pelican from "./Zeta Division/players/pelican_오세현.webp";
import ZetaDivision_ta1yo from "./Zeta Division/players/ta1yo_션 타이요 헨더슨.webp";
import ZetaDivision_박민기 from "./Zeta Division/players/박민기_1.webp";
import ZetaDivision_션타이요헨더슨 from "./Zeta Division/players/션타이요헨더슨_1.webp";
import ZetaDivision_신세원 from "./Zeta Division/players/신세원_1.webp";
import ZetaDivision_오세진 from "./Zeta Division/players/오세진_1.webp";
import ZetaDivision_오세현 from "./Zeta Division/players/오세현_1.webp";
import ZetaDivision_이의석 from "./Zeta Division/players/이의석_1.webp";
import ZetaDivision_이희성 from "./Zeta Division/players/이희성_1.webp";
import ZetaDivision_임영우 from "./Zeta Division/players/임영우_1.webp";

const teamPlayerData2 = {
  AllGamersGlobal: {
    players: {},
  },
  CrazyRaccoon: {
    players: {},
  },
  Geng: {
    players: {},
  },
  OldOcean: {
    players: {
      team: OldOcean_team,
    },
  },
  onsidegaming: {
    players: {
      achieve: onsidegaming_achieve,
      ado: onsidegaming_ado,
      attack: onsidegaming_attack,
      irony: onsidegaming_irony,
      Kilo: onsidegaming_Kilo,
      opener: onsidegaming_opener,
    },
  },
  PokerFace: {
    players: {
      team: PokerFace_team,
    },
  },
  T1: {
    players: {
      team: T1_team,
    },
  },
  TeamFalcons: {
    players: {
      chiyo: TeamFalcons_chiyo,
      fielder: TeamFalcons_fielder,
      Hanbin: TeamFalcons_Hanbin,
      mer1t: TeamFalcons_mer1t,
      proper: TeamFalcons_proper,
      Prophet: TeamFalcons_Prophet,
      sirmajed: TeamFalcons_sirmajed,
      smurf: TeamFalcons_smurf,
      SOMEONE: TeamFalcons_SOMEONE,
      stalk3r: TeamFalcons_stalk3r,
      Vindaim: TeamFalcons_Vindaim,
    },
  },
  VecSeongnam: {
    players: {
      Scarlett: VecSeongnam_Scarlett,
      seungan: VecSeongnam_seungan,
      WoochaN: VecSeongnam_WoochaN,
      XLIM: VecSeongnam_XLIM,
      ZeSin: VecSeongnam_ZeSin,
      김예한: VecSeongnam_김예한,
      박민호: VecSeongnam_박민호,
      이우찬: VecSeongnam_이우찬,
    },
  },
  ZetaDivision: {
    players: {
      alphayi: ZetaDivision_alphayi,
      bernar: ZetaDivision_bernar,
      FARMER: ZetaDivision_FARMER,
      flora: ZetaDivision_flora,
      pelican: ZetaDivision_pelican,
      ta1yo: ZetaDivision_ta1yo,
      박민기: ZetaDivision_박민기,
      션타이요헨더슨: ZetaDivision_션타이요헨더슨,
      신세원: ZetaDivision_신세원,
      오세진: ZetaDivision_오세진,
      오세현: ZetaDivision_오세현,
      이의석: ZetaDivision_이의석,
      이희성: ZetaDivision_이희성,
      임영우: ZetaDivision_임영우,
    },
  },
};

export default teamPlayerData2;
