// This file is auto-generated by generatePlayerImages.js. Do not edit manually.

import AllGamersGlobal_Ade from "./All Gamers Global/players/Ade/ade_이지환.webp";
import AllGamersGlobal_Algos05 from "./All Gamers Global/players/Algos05/profile.jpg";
import AllGamersGlobal_Cointree from "./All Gamers Global/players/Cointree/profile.jpg";
import AllGamersGlobal_Daemin from "./All Gamers Global/players/Daemin/profile.jpg";
import AllGamersGlobal_Dongsu from "./All Gamers Global/players/Dongsu/profile.jpg";
import AllGamersGlobal_Jasm1ne from "./All Gamers Global/players/Jasm1ne/jasm1ne_정종민.webp";
import AllGamersGlobal_LeeSooMin from "./All Gamers Global/players/LeeSooMin/LeeSooMin_이수민.webp";
import AllGamersGlobal_MAKA from "./All Gamers Global/players/MAKA/maka_오은석.webp";
import AllGamersGlobal_Mealgaru from "./All Gamers Global/players/Mealgaru/mealgaru_이정환.webp";
import AllGamersGlobal_SeonJun from "./All Gamers Global/players/SeonJun/seonjun_박선준.webp";
import CrazyRaccoon_CH0R0NG from "./Crazy Raccoon/players/CH0R0NG/CH0R0NG_성유민.webp";
import CrazyRaccoon_HeeSang from "./Crazy Raccoon/players/HeeSang/HeeSang_채희상1.webp";
import CrazyRaccoon_Jasper from "./Crazy Raccoon/players/Jasper/profile.jpg";
import CrazyRaccoon_Junbin from "./Crazy Raccoon/players/Junbin/junbin_박준빈1.webp";
import CrazyRaccoon_KNIFE from "./Crazy Raccoon/players/KNIFE/profile.jpg";
import CrazyRaccoon_Kong from "./Crazy Raccoon/players/Kong/Kong_손준영.webp";
import CrazyRaccoon_LIP from "./Crazy Raccoon/players/LIP/LIP_이재원1.webp";
import CrazyRaccoon_MAX from "./Crazy Raccoon/players/MAX/MAX_최수민1.webp";
import CrazyRaccoon_Moon from "./Crazy Raccoon/players/Moon/Moon_문병철.webp";
import CrazyRaccoon_Pavane from "./Crazy Raccoon/players/Pavane/Pavane_유현상.webp";
import CrazyRaccoon_Selly from "./Crazy Raccoon/players/Selly/profile.jpg";
import CrazyRaccoon_Shu from "./Crazy Raccoon/players/Shu/profile.jpg";
import CrazyRaccoon_Twinkl from "./Crazy Raccoon/players/Twinkl/profile.jpg";
import OldOcean_Becky from "./Old Ocean/players/Becky/becky_김일하.webp";
import OldOcean_Faith from "./Old Ocean/players/Faith/Faith_김홍규.webp";
import OldOcean_Gido from "./Old Ocean/players/Gido/profile.jpg";
import OldOcean_Gur3um from "./Old Ocean/players/Gur3um/Gur3um_전용민.webp";
import OldOcean_Kalios from "./Old Ocean/players/Kalios/profile.jpg";
import OldOcean_KIVIS from "./Old Ocean/players/KIVIS/KIVIS_정연우.webp";
import OldOcean_M1nut2 from "./Old Ocean/players/M1nut2/M1nut2_서민서.webp";
import OldOcean_Nenne from "./Old Ocean/players/Nenne/profile.jpg";
import OldOcean_Pelican from "./Old Ocean/players/Pelican/Pelican_오세현.webp";
import OldOcean_Probe from "./Old Ocean/players/Probe/probe_정준영.webp";
import OldOcean_RULER from "./Old Ocean/players/RULER/profile.jpg";
import OldOcean_ryujehong from "./Old Ocean/players/ryujehong/profile.jpg";
import OldOcean_Taejong from "./Old Ocean/players/Taejong/profile.jpg";
import OldOcean_Yang1 from "./Old Ocean/players/Yang1/profile.jpg";
import PokerFace_A1IEN from "./Poker Face/players/A1IEN/profile.jpg";
import PokerFace_Aester from "./Poker Face/players/Aester/profile.jpg";
import PokerFace_Aiden from "./Poker Face/players/Aiden/profile.jpg";
import PokerFace_Ares from "./Poker Face/players/Ares/profile.jpg";
import PokerFace_Arrow from "./Poker Face/players/Arrow/Arrow_박민석.webp";
import PokerFace_Aztac from "./Poker Face/players/Aztac/profile.jpg";
import PokerFace_Becky from "./Poker Face/players/Becky/profile.jpg";
import PokerFace_Belosrea from "./Poker Face/players/Belosrea/profile.jpg";
import PokerFace_BlueHaS from "./Poker Face/players/BlueHaS/profile.jpg";
import PokerFace_CARU from "./Poker Face/players/CARU/profile.jpg";
import PokerFace_ChoiSehwan from "./Poker Face/players/ChoiSehwan/profile.jpg";
import PokerFace_D0nghun from "./Poker Face/players/D0nghun/profile.jpg";
import PokerFace_D4RT from "./Poker Face/players/D4RT/profile.jpg";
import PokerFace_Daphne from "./Poker Face/players/Daphne/profile.jpg";
import PokerFace_ENOCASS from "./Poker Face/players/ENOCASS/profile.jpg";
import PokerFace_Exy from "./Poker Face/players/Exy/profile.jpg";
import PokerFace_Faith from "./Poker Face/players/Faith/profile.jpg";
import PokerFace_Finale from "./Poker Face/players/Finale/profile.jpg";
import PokerFace_FiXa from "./Poker Face/players/FiXa/profile.jpg";
import PokerFace_Gur3um from "./Poker Face/players/Gur3um/profile.jpg";
import PokerFace_HEISER from "./Poker Face/players/HEISER/profile.jpg";
import PokerFace_Hidden from "./Poker Face/players/Hidden/profile.jpg";
import PokerFace_HoChiLee from "./Poker Face/players/HoChiLee/profile.jpg";
import PokerFace_Ir1s from "./Poker Face/players/Ir1s/Ir1s_김승현.webp";
import PokerFace_JaeWoo from "./Poker Face/players/JaeWoo/profile.jpg";
import PokerFace_Jasm1ne from "./Poker Face/players/Jasm1ne/profile.jpg";
import PokerFace_LeGo from "./Poker Face/players/LeGo/profile.jpg";
import PokerFace_Minamul from "./Poker Face/players/Minamul/profile.jpg";
import PokerFace_Misin from "./Poker Face/players/Misin/profile.jpg";
import PokerFace_Morey from "./Poker Face/players/Morey/profile.jpg";
import PokerFace_MuZe from "./Poker Face/players/MuZe/profile.jpg";
import PokerFace_Nerd from "./Poker Face/players/Nerd/profile.jpg";
import PokerFace_PEPPI from "./Poker Face/players/PEPPI/PEPPI_김노아.webp";
import PokerFace_premier from "./Poker Face/players/premier/profile.jpg";
import PokerFace_Presia from "./Poker Face/players/Presia/profile.jpg";
import PokerFace_Probe from "./Poker Face/players/Probe/profile.jpg";
import PokerFace_Proud from "./Poker Face/players/Proud/profile.jpg";
import PokerFace_rOar from "./Poker Face/players/rOar/profile.jpg";
import PokerFace_Seowhi from "./Poker Face/players/Seowhi/profile.jpg";
import PokerFace_Simple from "./Poker Face/players/Simple/profile.jpg";
import PokerFace_Sp1nel from "./Poker Face/players/Sp1nel/profile.jpg";
import PokerFace_SP1NT from "./Poker Face/players/SP1NT/profile.jpg";
import PokerFace_Spectra from "./Poker Face/players/Spectra/profile.jpg";
import PokerFace_Valentine from "./Poker Face/players/Valentine/profile.jpg";
import PokerFace_Victoria from "./Poker Face/players/Victoria/profile.jpg";
import PokerFace_YangJun from "./Poker Face/players/YangJun/profile.jpg";
import T1_A1IEN from "./T1/players/A1IEN/profile.jpg";
import T1_Ap3ach from "./T1/players/Ap3ach/profile.jpg";
import T1_Avast from "./T1/players/Avast/Avast_코너 프린스.webp";
import T1_Clestyn from "./T1/players/Clestyn/profile.jpg";
import T1_D0NGHAK from "./T1/players/D0NGHAK/DONGHAK_김민성.webp";
import T1_Fleta from "./T1/players/Fleta/Fleta_김병선.webp";
import T1_Kadalis from "./T1/players/Kadalis/profile.jpg";
import T1_Krillin from "./T1/players/Krillin/profile.jpg";
import T1_Na1st from "./T1/players/Na1st/profile.jpg";
import T1_PERFACT from "./T1/players/PERFACT/profile.jpg";
import T1_Physics from "./T1/players/Physics/profile.jpg";
import T1_Proud from "./T1/players/Proud/profile.jpg";
import T1_QoQ from "./T1/players/QoQ/profile.jpg";
import T1_RpEN from "./T1/players/RpEN/profile.jpg";
import T1_RUSH from "./T1/players/RUSH/RUSH_윤희원.webp";
import T1_SixFeet from "./T1/players/SixFeet/profile.jpg";
import T1_skewed from "./T1/players/skewed/profile.jpg";
import T1_Sven from "./T1/players/Sven/profile.jpg";
import T1_TTACKER from "./T1/players/TTACKER/profile.jpg";
import T1_Unique from "./T1/players/Unique/profile.jpg";
import T1_vigilante from "./T1/players/vigilante/profile.jpg";
import T1_Viper from "./T1/players/Viper/profile.jpg";
import T1_Zeerocious from "./T1/players/Zeerocious/profile.jpg";
import T1_ZEST from "./T1/players/ZEST/profile.jpg";
import OldOcean_team from "./Old Ocean/players/team_logo.png";
import onsidegaming_achieve from "./onside gaming/players/achieve_서상원.webp";
import onsidegaming_ado from "./onside gaming/players/ado_천기현.webp";
import onsidegaming_attack from "./onside gaming/players/attack_김준화.webp";
import onsidegaming_irony from "./onside gaming/players/irony_김백강.webp";
import onsidegaming_Kilo from "./onside gaming/players/Kilo_정진우.webp";
import onsidegaming_opener from "./onside gaming/players/opener_안기범.webp";
import PokerFace_team from "./Poker Face/players/team_logo.png";
import T1_team from "./T1/players/team_logo.png";
import TeamFalcons_chiyo from "./Team Falcons/players/chiyo_한현석.webp";
import TeamFalcons_fielder from "./Team Falcons/players/fielder_권준.webp";
import TeamFalcons_Hanbin from "./Team Falcons/players/Hanbin_최한빈.webp";
import TeamFalcons_mer1t from "./Team Falcons/players/mer1t_최태민.webp";
import TeamFalcons_proper from "./Team Falcons/players/proper_김동현.webp";
import TeamFalcons_Prophet from "./Team Falcons/players/Prophet_김현빈.webp";
import TeamFalcons_sirmajed from "./Team Falcons/players/sirmajed_마지드알라시드.webp";
import TeamFalcons_smurf from "./Team Falcons/players/smurf_유명환_1.webp";
import TeamFalcons_SOMEONE from "./Team Falcons/players/SOMEONE_함정완.webp";
import TeamFalcons_stalk3r from "./Team Falcons/players/stalk3r_정학용.webp";
import TeamFalcons_Vindaim from "./Team Falcons/players/Vindaim_박준우.webp";
import VecSeongnam_Scarlett from "./Vec Seongnam/players/Scarlett_권문경.webp";
import VecSeongnam_seungan from "./Vec Seongnam/players/seungan_이승안.webp";
import VecSeongnam_WoochaN from "./Vec Seongnam/players/WoochaN_이우찬.webp";
import VecSeongnam_XLIM from "./Vec Seongnam/players/XLIM_윤지후.webp";
import VecSeongnam_ZeSin from "./Vec Seongnam/players/ZeSin_송윤진.webp";
import VecSeongnam_김예한 from "./Vec Seongnam/players/김예한_1.webp";
import VecSeongnam_박민호 from "./Vec Seongnam/players/박민호_1.webp";
import VecSeongnam_이우찬 from "./Vec Seongnam/players/이우찬_1.webp";
import ZetaDivision_alphayi from "./Zeta Division/players/alphayi_김준1.webp";
import ZetaDivision_bernar from "./Zeta Division/players/bernar_신세원2.webp";
import ZetaDivision_FARMER from "./Zeta Division/players/FARMER_김예한.webp";
import ZetaDivision_flora from "./Zeta Division/players/flora_임영우.webp";
import ZetaDivision_pelican from "./Zeta Division/players/pelican_오세현.webp";
import ZetaDivision_ta1yo from "./Zeta Division/players/ta1yo_션 타이요 헨더슨.webp";
import ZetaDivision_박민기 from "./Zeta Division/players/박민기_1.webp";
import ZetaDivision_션타이요헨더슨 from "./Zeta Division/players/션타이요헨더슨_1.webp";
import ZetaDivision_신세원 from "./Zeta Division/players/신세원_1.webp";
import ZetaDivision_오세진 from "./Zeta Division/players/오세진_1.webp";
import ZetaDivision_오세현 from "./Zeta Division/players/오세현_1.webp";
import ZetaDivision_이의석 from "./Zeta Division/players/이의석_1.webp";
import ZetaDivision_이희성 from "./Zeta Division/players/이희성_1.webp";
import ZetaDivision_임영우 from "./Zeta Division/players/임영우_1.webp";

const playerImages = {
  AllGamersGlobal: {
    players: {
      Ade: AllGamersGlobal_Ade,
      Algos05: AllGamersGlobal_Algos05,
      Cointree: AllGamersGlobal_Cointree,
      Daemin: AllGamersGlobal_Daemin,
      Dongsu: AllGamersGlobal_Dongsu,
      Jasm1ne: AllGamersGlobal_Jasm1ne,
      LeeSooMin: AllGamersGlobal_LeeSooMin,
      MAKA: AllGamersGlobal_MAKA,
      Mealgaru: AllGamersGlobal_Mealgaru,
      SeonJun: AllGamersGlobal_SeonJun,
    },
  },
  CrazyRaccoon: {
    players: {
      CH0R0NG: CrazyRaccoon_CH0R0NG,
      HeeSang: CrazyRaccoon_HeeSang,
      Jasper: CrazyRaccoon_Jasper,
      Junbin: CrazyRaccoon_Junbin,
      KNIFE: CrazyRaccoon_KNIFE,
      Kong: CrazyRaccoon_Kong,
      LIP: CrazyRaccoon_LIP,
      MAX: CrazyRaccoon_MAX,
      Moon: CrazyRaccoon_Moon,
      Pavane: CrazyRaccoon_Pavane,
      Selly: CrazyRaccoon_Selly,
      Shu: CrazyRaccoon_Shu,
      Twinkl: CrazyRaccoon_Twinkl,
    },
  },
  Geng: {
    players: {},
  },
  OldOcean: {
    players: {
      Becky: OldOcean_Becky,
      Faith: OldOcean_Faith,
      Gido: OldOcean_Gido,
      Gur3um: OldOcean_Gur3um,
      Kalios: OldOcean_Kalios,
      KIVIS: OldOcean_KIVIS,
      M1nut2: OldOcean_M1nut2,
      Nenne: OldOcean_Nenne,
      Pelican: OldOcean_Pelican,
      Probe: OldOcean_Probe,
      RULER: OldOcean_RULER,
      ryujehong: OldOcean_ryujehong,
      Taejong: OldOcean_Taejong,
      Yang1: OldOcean_Yang1,
    },
  },
  onsidegaming: {
    players: {
      achieve: onsidegaming_achieve,
      ado: onsidegaming_ado,
      attack: onsidegaming_attack,
      irony: onsidegaming_irony,
      Kilo: onsidegaming_Kilo,
      opener: onsidegaming_opener,
    },
  },
  PokerFace: {
    players: {
      A1IEN: PokerFace_A1IEN,
      Aester: PokerFace_Aester,
      Aiden: PokerFace_Aiden,
      Ares: PokerFace_Ares,
      Arrow: PokerFace_Arrow,
      Aztac: PokerFace_Aztac,
      Becky: PokerFace_Becky,
      Belosrea: PokerFace_Belosrea,
      BlueHaS: PokerFace_BlueHaS,
      CARU: PokerFace_CARU,
      ChoiSehwan: PokerFace_ChoiSehwan,
      D0nghun: PokerFace_D0nghun,
      D4RT: PokerFace_D4RT,
      Daphne: PokerFace_Daphne,
      ENOCASS: PokerFace_ENOCASS,
      Exy: PokerFace_Exy,
      Faith: PokerFace_Faith,
      Finale: PokerFace_Finale,
      FiXa: PokerFace_FiXa,
      Gur3um: PokerFace_Gur3um,
      HEISER: PokerFace_HEISER,
      Hidden: PokerFace_Hidden,
      HoChiLee: PokerFace_HoChiLee,
      Ir1s: PokerFace_Ir1s,
      JaeWoo: PokerFace_JaeWoo,
      Jasm1ne: PokerFace_Jasm1ne,
      LeGo: PokerFace_LeGo,
      Minamul: PokerFace_Minamul,
      Misin: PokerFace_Misin,
      Morey: PokerFace_Morey,
      MuZe: PokerFace_MuZe,
      Nerd: PokerFace_Nerd,
      PEPPI: PokerFace_PEPPI,
      premier: PokerFace_premier,
      Presia: PokerFace_Presia,
      Probe: PokerFace_Probe,
      Proud: PokerFace_Proud,
      rOar: PokerFace_rOar,
      Seowhi: PokerFace_Seowhi,
      Simple: PokerFace_Simple,
      Sp1nel: PokerFace_Sp1nel,
      SP1NT: PokerFace_SP1NT,
      Spectra: PokerFace_Spectra,
      Valentine: PokerFace_Valentine,
      Victoria: PokerFace_Victoria,
      YangJun: PokerFace_YangJun,
    },
  },
  T1: {
    players: {
      A1IEN: T1_A1IEN,
      Ap3ach: T1_Ap3ach,
      Avast: T1_Avast,
      Clestyn: T1_Clestyn,
      D0NGHAK: T1_D0NGHAK,
      Fleta: T1_Fleta,
      Kadalis: T1_Kadalis,
      Krillin: T1_Krillin,
      Na1st: T1_Na1st,
      PERFACT: T1_PERFACT,
      Physics: T1_Physics,
      Proud: T1_Proud,
      QoQ: T1_QoQ,
      RpEN: T1_RpEN,
      RUSH: T1_RUSH,
      SixFeet: T1_SixFeet,
      skewed: T1_skewed,
      Sven: T1_Sven,
      TTACKER: T1_TTACKER,
      Unique: T1_Unique,
      vigilante: T1_vigilante,
      Viper: T1_Viper,
      Zeerocious: T1_Zeerocious,
      ZEST: T1_ZEST,
    },
  },
  TeamFalcons: {
    players: {
      chiyo: TeamFalcons_chiyo,
      fielder: TeamFalcons_fielder,
      Hanbin: TeamFalcons_Hanbin,
      mer1t: TeamFalcons_mer1t,
      proper: TeamFalcons_proper,
      Prophet: TeamFalcons_Prophet,
      sirmajed: TeamFalcons_sirmajed,
      smurf: TeamFalcons_smurf,
      SOMEONE: TeamFalcons_SOMEONE,
      stalk3r: TeamFalcons_stalk3r,
      Vindaim: TeamFalcons_Vindaim,
    },
  },
  VecSeongnam: {
    players: {
      Scarlett: VecSeongnam_Scarlett,
      seungan: VecSeongnam_seungan,
      WoochaN: VecSeongnam_WoochaN,
      XLIM: VecSeongnam_XLIM,
      ZeSin: VecSeongnam_ZeSin,
      김예한: VecSeongnam_김예한,
      박민호: VecSeongnam_박민호,
      이우찬: VecSeongnam_이우찬,
    },
  },
  ZetaDivision: {
    players: {
      alphayi: ZetaDivision_alphayi,
      bernar: ZetaDivision_bernar,
      FARMER: ZetaDivision_FARMER,
      flora: ZetaDivision_flora,
      pelican: ZetaDivision_pelican,
      ta1yo: ZetaDivision_ta1yo,
      박민기: ZetaDivision_박민기,
      션타이요헨더슨: ZetaDivision_션타이요헨더슨,
      신세원: ZetaDivision_신세원,
      오세진: ZetaDivision_오세진,
      오세현: ZetaDivision_오세현,
      이의석: ZetaDivision_이의석,
      이희성: ZetaDivision_이희성,
      임영우: ZetaDivision_임영우,
    },
  },
};

export default playerImages;
