const fs = require("fs");
const path = require("path");

// --- 설정 부분 ---
const rootImageDir = path.join(
  __dirname,
  "../frontend/public/images/game_team"
);
const outputPath = path.join(rootImageDir, "index.ts");

// --- 메인 로직 ---
try {
  const teams = fs
    .readdirSync(rootImageDir)
    .filter((file) => fs.statSync(path.join(rootImageDir, file)).isDirectory());

  let importStatements = "";
  const exportObject = {};

  teams.forEach((teamName) => {
    const sanitizedTeamName = teamName.replace(/[^a-zA-Z0-9]/g, "");
    exportObject[sanitizedTeamName] = { players: {} };

    const playersDir = path.join(rootImageDir, teamName, "players");
    if (fs.existsSync(playersDir)) {
      const players = fs
        .readdirSync(playersDir)
        .filter((file) =>
          fs.statSync(path.join(playersDir, file)).isDirectory()
        );

      players.forEach((playerName) => {
        const sanitizedPlayerName = playerName.replace(/[^a-zA-Z0-9]/g, "");
        const playerImageDir = path.join(playersDir, playerName);
        const imageFiles = fs
          .readdirSync(playerImageDir)
          .filter((file) => /\.(png|jpe?g|svg|webp)$/.test(file));

        if (imageFiles.length > 0) {
          const imageName = imageFiles[0];
          const importName = `${sanitizedTeamName}_${sanitizedPlayerName}`;
          const importPath = `./${teamName}/players/${playerName}/${imageName}`;

          importStatements += `import ${importName} from '${importPath}';\n`;
          exportObject[sanitizedTeamName].players[sanitizedPlayerName] =
            importName;
        }
      });
    }
  });

  // JavaScript 객체를 문자열로 변환하여 파일에 쓸 준비
  let exportString = JSON.stringify(exportObject, null, 4)
    .replace(/"([^"]+)":/g, "$1:") // 키의 따옴표 제거
    .replace(/"([^"]+)"/g, "$1"); // 값의 따옴표 제거 (변수 이름이므로)

  const fileContent = `// This file is auto-generated by generatePlayerImages.js. Do not edit manually.

${importStatements}
const playerImages = ${exportString};

export default playerImages;
`;

  fs.writeFileSync(outputPath, fileContent, "utf8");

  console.log(`✅ Successfully generated ${outputPath}`);
} catch (error) {
  console.error("❌ Error generating player image exports:", error);
}
